export default {
darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "surface-container-highest": "#e3e1ea",
                    "on-secondary": "#ffffff",
                    "tertiary-fixed-dim": "#ffb784",
                    "surface": "#fbf8ff",
                    "on-tertiary": "#ffffff",
                    "inverse-primary": "#bcc2ff",
                    "tertiary-container": "#8f4700",
                    "surface-bright": "#fbf8ff",
                    "on-surface": "#1a1b22",
                    "on-tertiary-container": "#ffc7a2",
                    "secondary": "#565c84",
                    "surface-container-low": "#f4f2fc",
                    "on-secondary-container": "#51577f",
                    "error-container": "#ffdad6",
                    "on-tertiary-fixed": "#301400",
                    "surface-container-high": "#e9e7f0",
                    "tertiary-fixed": "#ffdcc6",
                    "surface-dim": "#dbd9e2",
                    "secondary-container": "#c9cffd",
                    "inverse-surface": "#2f3037",
                    "on-background": "#1a1b22",
                    "secondary-fixed": "#dee0ff",
                    "on-primary-container": "#cbcfff",
                    "error": "#ba1a1a",
                    "primary-container": "#4551af",
                    "inverse-on-surface": "#f2eff9",
                    "surface-variant": "#e3e1ea",
                    "primary": "#2b3896",
                    "outline": "#757684",
                    "outline-variant": "#c5c5d4",
                    "on-secondary-fixed": "#12183d",
                    "tertiary": "#6c3400",
                    "primary-fixed": "#dfe0ff",
                    "on-primary-fixed-variant": "#303c9a",
                    "surface-container-lowest": "#ffffff",
                    "on-primary": "#ffffff",
                    "surface-container": "#efedf6",
                    "on-error-container": "#93000a",
                    "secondary-fixed-dim": "#bec4f2",
                    "on-surface-variant": "#454652",
                    "on-secondary-fixed-variant": "#3e446b",
                    "on-primary-fixed": "#000c62",
                    "on-tertiary-fixed-variant": "#713700",
                    "on-error": "#ffffff",
                    "surface-tint": "#4955b3",
                    "background": "#fbf8ff",
                    "primary-fixed-dim": "#bcc2ff"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "fontFamily": {
                    "headline": ["Manrope"],
                    "body": ["Inter"],
                    "label": ["Inter"]
            }
          },
        },
}